-- ejercicio 1 
select CARGO, count(idcliente) as CUENTA_CLIENTES
from CLIENTE
group by CARGO
order by CARGO; 

-- EJERCICIO 2
UPDATE PRODUCTO SET STOCK=STOCK+100
WHERE IDPRODUCTO=3;

-- EJERCICIO 3
SELECT IDPEDIDO, FECHAPEDIDO, FECHAENTREGA, CIA, CONTACTO
FROM CLIENTE INNER JOIN PEDIDO
ON CLIENTE.IDCLIENTE  = PEDIDO.IDCLIENTE
ORDER BY IDPEDIDO;

-- EJERCICIO 4
SELECT PEDIDO.IDPEDIDO, FECHAPEDIDO, FECHAENTREGA, CIA, CONTACTO,
	SUM(PRECIO*UNIDADES - PRECIO*UNIDADES*DESCUENTO) AS IMPORTE 
FROM (CLIENTE INNER JOIN PEDIDO
ON CLIENTE.IDCLIENTE  = PEDIDO.IDCLIENTE)
INNER JOIN DETALLE 
ON DETALLE.IDPEDIDO = PEDIDO.IDPEDIDO
GROUP BY PEDIDO.IDPEDIDO
ORDER BY PEDIDO.IDPEDIDO;

-- EJERCICIO 5
SET SQL_SAFE_UPDATES = 0;
DELETE FROM PRODUCTO 
WHERE NOMBRE = 'Sirope de regaliz';
SET SQL_SAFE_UPDATES = 1;
